headerscheck: Ignore Windows-specific header
Ignore src/include/port/win32/sys/resource.h.  At least on macOS,
including this results in warnings and errors because of duplication
with system headers:

../src/include/port/win32/sys/resource.h:10:9: warning: 'RUSAGE_CHILDREN' redefined
../src/include/port/win32/sys/resource.h:16:1: error: redefinition of struct or union 'struct rusage'

Since we are also not checking similar system-replacement headers for
Windows, it makes sense to exclude this one, too.

Reviewed-by: Tom Lane <tgl@sss.pgh.pa.us>
Discussion: https://www.postgresql.org/message-id/flat/1127775.1754417387%40sss.pgh.pa.us